### PR TITLE
fix: support noise model in batch_execute

### PR DESCRIPTION
**Pull request by yitchen-tim**
*Issue #, if available:* https://github.com/aws/amazon-braket-pennylane-plugin-python/issues/176

*Description of changes:*
Move code of applying noise_model to circuit translation. Both `execute` and `batch_execute` call circuit translation before running, assuring the noise model is applied to circuits.

*Testing done:*
unit tests

## Merge Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your pull request._

#### General

- [x] I have read the [CONTRIBUTING](https://github.com/aws/amazon-braket-pennylane-plugin-python/blob/main/CONTRIBUTING.md) doc
- [x] I used the commit message format described in [CONTRIBUTING](https://github.com/aws/amazon-braket-pennylane-plugin-python/blob/main/CONTRIBUTING.md#commit-your-change)
- [x] I have updated any necessary documentation, including [READMEs](https://github.com/aws/amazon-braket-pennylane-plugin-python/blob/main/README.md) and [API docs](https://github.com/aws/amazon-braket-pennylane-plugin-python/blob/main/CONTRIBUTING.md#documentation-guidelines) (if appropriate)

#### Tests

- [x] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [x] I have checked that my tests are not configured for a specific region or account (if appropriate)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by kshyatt-aws** [comment]
Can you also add noise model application in the `apply` class method? I think that doesn't use `_pl_to_braket_circuit` so if a user goes through that path (e.g. if they're using shadows) the noise model won't be applied.

**Comment by yitchen-tim** [comment]
CI fails because of breaking change in autograph: https://github.com/HIPS/autograd/issues/601

**Comment by yitchen-tim** [comment]
CI fails because of breaking change in autograph: https://github.com/HIPS/autograd/issues/601

**Comment by yitchen-tim** [comment]
redo checks and all checks passed

**Review by speller26 — DISMISSED** [review]
Looks good, but conflict needs resolution

**Review by speller26 — APPROVED** [review]

**Pull request merged**
