### PR TITLE
Add support for new custom measurements

### PR DESCRIPTION
**Pull request by AlbertMitjans**
*Issue #, if available:*

*Description of changes:* Stop instantiating `MeasurementProcess` directly. Use the corresponding measurement's class instead.

*Testing done:* Yes

## Merge Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your pull request._

#### General

- [x] I have read the [CONTRIBUTING](https://github.com/aws/amazon-braket-pennylane-plugin-python/blob/main/CONTRIBUTING.md) doc
- [x] I used the commit message format described in [CONTRIBUTING](https://github.com/aws/amazon-braket-pennylane-plugin-python/blob/main/CONTRIBUTING.md#commit-your-change)
- [x] I have updated any necessary documentation, including [READMEs](https://github.com/aws/amazon-braket-pennylane-plugin-python/blob/main/README.md) and [API docs](https://github.com/aws/amazon-braket-pennylane-plugin-python/blob/main/CONTRIBUTING.md#documentation-guidelines) (if appropriate)

#### Tests

- [x] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [x] I have checked that my tests are not configured for a specific region or account (if appropriate)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by mdpratt** [comment]
We will take a look at this today.

**Review by kshitijc — COMMENTED** [review]
Thanks for the PR @AlbertMitjans!
* Would you need to import these new classes here before you use them ?
* Does this require change in the source code [here](https://github.com/aws/amazon-braket-pennylane-plugin-python/blob/main/src/braket/pennylane_plugin/translation.py) to handle the new class types being instantiated ?
* Would this require updates in setup.py to [indicate constraints on the version](https://github.com/aws/amazon-braket-pennylane-plugin-python/blob/main/setup.py#L31) which introduced these new classes in Pennylane?

**Comment by AlbertMitjans** [comment]
Hi @kshitijc! Here are the answers to your questions:

> Would you need to import these new classes here before you use them ?

Yes, my mistake. However in my last commit I changed the tests to use the top-level functions (`qml.probs`) instead of the classes directly (`ProbabilityMP`). This way the tests will work with older PennyLane versions.

> Does this require change in the source code [here](https://github.com/aws/amazon-braket-pennylane-plugin-python/blob/main/src/braket/pennylane_plugin/translation.py) to handle the new class types being instantiated ?

It is not mandatory, given that we still use `ObservablesReturnTypes` for backward compatibility. However it would be nice to handle the new class types because the `return_type` attribute of the `MeasurementProcess` will get deprecated soon. 

> Would this require updates in setup.py to [indicate constraints on the version](https://github.com/aws/amazon-braket-pennylane-plugin-python/blob/main/setup.py#L31) which introduced these new classes in Pennylane?

No, with the last changes (use `qml.probs` instead of `ProbabilityMP`) the tests will still work with older PennyLane versions.

**Comment by kshitijc** [comment]
Thanks for the updates @AlbertMitjans!

> However it would be nice to handle the new class types because the return_type attribute of the MeasurementProcess will get deprecated soon.
Given that there are plans to deprecate this attribute, would it make sense to make these changes now? Or should we wait?

Also, the tests are failing since Pennylane appears to be using the Walrus operator now, which doesn't work with Python 3.7. Seems like Pennylane is dropping support for Python 3.7, and we'd probably have to do that here for the plugin as well. 

Does Pennylane have a way to inform its consumers of such breaking changes prior to these being released?

**Comment by AlbertMitjans** [comment]
> Given that there are plans to deprecate this attribute, would it make sense to make these changes now? Or should we wait?

Yes! It would definitely make sense to make these changes now!

> Does Pennylane have a way to inform its consumers of such breaking changes prior to these being released?

Currently, we do this via our [blog post](https://pennylane.ai/blog/), [twitter thread](https://twitter.com/PennyLaneAI), and [deprecations page](https://docs.pennylane.ai/en/stable/development/deprecations.html).

**Review by math411 — APPROVED** [review]

**Review by speller26 — APPROVED** [review]

**Pull request merged**
