### PR TITLE
fix: remove minified version of jquery and bootstrap

### PR DESCRIPTION
**Pull request by ajberdy**
*Issue #, if available:*

*Description of changes:*

Remove minified version of jquery and bootstrap

*Testing done:*

Rendered docs and checked to make sure the layout looked correct and that search was still working

## Merge Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your pull request._

#### General

- [x] I have read the [CONTRIBUTING](https://github.com/aws/amazon-braket-pennylane-plugin-python/blob/main/CONTRIBUTING.md) doc
- [x] I used the commit message format described in [CONTRIBUTING](https://github.com/aws/amazon-braket-pennylane-plugin-python/blob/main/CONTRIBUTING.md#commit-your-change)
- [x] I have updated any necessary documentation, including [READMEs](https://github.com/aws/amazon-braket-pennylane-plugin-python/blob/main/README.md) and [API docs](https://github.com/aws/amazon-braket-pennylane-plugin-python/blob/main/CONTRIBUTING.md#documentation-guidelines) (if appropriate)

#### Tests

- [x] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [x] I have checked that my tests are not configured for a specific region or account (if appropriate)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by speller26** [comment]
Adding @mariaschuld and @josh146 to check if these removals are okay for the theme

**Review by josh146 — COMMENTED** [review]
removing jqeury and bootstrap should be fine, since the HTML uses a CDN to import them 👍 

The only one that will cause issues is Nanoscroller, since the `layout.html` site is importing this file directly, see

https://github.com/aws/amazon-braket-pennylane-plugin-python/blob/dc2c2aa535ea1f0fd885f75ced7582525e603cfc/doc/xanadu_theme/layout.html#L18

https://github.com/aws/amazon-braket-pennylane-plugin-python/blob/dc2c2aa535ea1f0fd885f75ced7582525e603cfc/doc/xanadu_theme/layout.html#L232

If these lines are updated to load Nanoscroller via the CDN (see https://cdnjs.com/libraries/jquery.nanoscroller), this should then be fine.

**Comment by mariaschuld** [comment]
I have no opinion on this, since i do not know what half the terms mean :)

**Comment by ajberdy** [comment]
Should I also replace the static nanoscroller css import with a cdn or should I leave that part as is?

**Review by josh146 — APPROVED** [review]
> Should I also replace the static nanoscroller css import with a cdn or should I leave that part as is?

Either should work! No major preference on my side. Apart from that, looks good!

**Review by speller26 — APPROVED** [review]

**Pull request merged**
